
export const sample_foods:any[]=[
    {
        id:'1',
        name: 'Pizza Pepperoni',
        cookTime: '10-20',
        price: 10,
        favorite: true,
        origins: ['italy'],
        stars: 4.5,
        imageUrl: 'assets/food-1.jpg',
        tags: ['FastFood', 'Pizza', 'Lunch'],
      },
      {
        id:'2',
        name: 'Meatball',
        price: 20,
        cookTime: '20-30',
        favorite: true,
        origins: ['persia', 'middle east', 'china'],
        stars: 4.7,
        imageUrl: 'assets/food-2.jpg',
        tags: ['SlowFood', 'Lunch'],
      },
      {
        id:'3',
        name: 'Hamburger',
        price: 5,
        cookTime: '10-15',
        favorite: false,
        origins: ['germany', 'us'],
        stars: 3.5,
        imageUrl: 'assets/food-3.jpg',
        tags: ['FastFood', 'Hamburger'],
      },
      {
        id:'4',
        name: 'Fried Potatoes',
        price: 2,
        cookTime: '15-20',
        favorite: true,
        origins: ['belgium', 'france'],
        stars: 3.3,
        imageUrl: 'assets/food-4.jpg',
        tags: ['FastFood', 'Fry'],
      },
      {
        id:'5',
        name: 'Chicken Soup',
        price: 11,
        cookTime: '40-50',
        favorite: false,
        origins: ['india', 'asia'],
        stars: 3.0,
        imageUrl: 'assets/food-5.jpg',
        tags: ['SlowFood', 'Soup'],
      },
      {
        id:'6',
        name: 'Vegetables Pizza',
        price: 9,
        cookTime: '40-50',
        favorite: false,
        origins: ['italy'],
        stars: 4.0,
        imageUrl: 'assets/food-6.jpg',
        tags: ['FastFood', 'Pizza', 'Lunch'],
      },
      {
        id:'7',
        name: 'Vegetables Pizza',
        price: 2,
        cookTime: '40-50',
        favorite: false,
        origins: ['USA'],
        stars: 4.0,
        imageUrl: 'assets/food-6.jpg',
        tags: ['FastFood', 'Pizza', 'Lunch'],
      },
      {
        id:'8',
        name:'Chicken Rice',
        price: 15,
        cookTime: '40-50',
        favorite: false,
        origins: ['India'],
        stars: 4.0,
        imageUrl: 'assets/food-8.jpg',
        tags: ['FastFood', 'Fry', 'Lunch'],
      },
      {
        id:'9',
        name: 'Chicken Biriyani',
        price: 20,
        cookTime: '40-50',
        favorite: true,
        origins: ['Russia'],
        stars: 4.0,
        imageUrl: 'assets/food-9.jpg',
        tags: ['FastFood', 'Lunch'],
      },
      {
        id:'10',
        name: 'Naan',
        price: 10,
        cookTime: '40-50',
        favorite: false,
        origins: ['India'],
        stars: 4.0,
        imageUrl: 'assets/food-10.jpg',
        tags: ['FastFood',  'Lunch'],
      },
      {
        id:'11',
        name: 'Pasta',
        price: 3,
        cookTime: '40-50',
        favorite: false,
        origins: ['Dubai'],
        stars: 4.0,
        imageUrl: 'assets/food-11.jpg',
        tags: ['FastFood' ],
      },
      {
        id:'12',
        name: ' Veg-Sandwidth',
        price: 5,
        cookTime: '40-50',
        favorite: false,
        origins: ['italy'],
        stars: 4.0,
        imageUrl: 'assets/food-12.jpg',
        tags: ['FastFood',  'Lunch'],
      },
      {
        id:'13',
        name: 'Parotta',
        price: 5,
        cookTime: '40-50',
        favorite: false,
        origins: ['India'],
        stars: 4.0,
        imageUrl: 'assets/food-13.jpg',
        tags: ['FastFood', 'Lunch','SlowFood'],
      },
      {
        id:'14',
        name: 'Chicken Grill',
        price: 16,
        cookTime: '40-50',
        favorite: false,
        origins: ['South africa'],
        stars: 4.0,
        imageUrl: 'assets/food-14.jpg',
        tags: ['FastFood', 'Lunch','fry'],
      },
      {
        id:'15',
        name: 'Chicken Manjurian',
        price: 10,
        cookTime: '30-50',
        favorite: false,
        origins: ['india'],
        stars: 4.0,
        imageUrl: 'assets/food-15.jpg',
        tags: ['FastFood', 'Lunch','fry'],
      }
      
]

  export const sample_tags:any[] = [
    { name: 'All', count: 15},
    { name: 'FastFood', count: 13 },
    { name: 'Pizza', count: 3 },
    { name: 'Lunch', count: 11},
    { name: 'SlowFood', count: 3 },
    { name: 'Hamburger', count: 1 },
    { name: 'Fry', count: 2 },
    { name: 'Soup', count: 1 },
  ]


  export const sample_users: any[] = [
    {
      name: "Brijesh",
      email: "brijesh@gmail.com",
      password: "12345",
      address: "Salem",
      isAdmin: true,
    },
    {
      name: "Krithika",
      email: "krithika@gmail.com",
      password: "12345",
      address: "Salem",
      isAdmin: false,
    },
  ];
